{
 "title": "SoftEther VPN",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Hub Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "avg(softether_online) by (hub)", "legendFormat": "{{hub}}" }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(softether_sessions_client) by (hub)",
     "legendFormat": "{{hub}}"
    }
   ]
  },
  {
   "title": "MAC Table",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(softether_mac_tables) by (hub)",
     "legendFormat": "{{hub}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "IP Table",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "sum(softether_ip_tables) by (hub)",
     "legendFormat": "{{hub}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Hub Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(softether_incoming_broadcast_bytes[1m]) + rate(softether_incoming_unicast_bytes[1m])) by (hub)",
     "legendFormat": "incoming-{{hub}}"
    },
    {
     "expr": "sum(rate(softether_outgoing_broadcast_bytes[1m]) + rate(softether_outgoing_unicast_bytes[1m])) by (hub)",
     "legendFormat": "outgoing-{{hub}}"
    }
   ]
  },
  {
   "title": "User Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(softether_user_transfer_bytes{user!=\"Local Bridge\", user !=\"SecureNAT\"}[1m])) by (user)",
     "legendFormat": "{{user}}"
    }
   ]
  }
 ]
}